
#/*FONT*/#

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

shell_integration enabled
repaint_delay 0
sync_to_monitor yes

include ~/.cache/wal/colors-kitty.conf
